#!/bin/bash
[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"
stuff=$( cat $input ) 
IFS=$'\n' noiceWords=($stuff)
len=${#noiceWords[@]}
IFS=$' '
numberOfLines=-1
originNumberOfLines=0
lines=()
while IFS='' read -r line || [[ -n "$line" ]]; do
	if [ "$numberOfLines" -eq "-1" ]; then
		#first line
		originNumberOfLines=$line
		((numberOfLines++))
		continue
	fi
	arr=($line)
	i=0
	isInNoiceWords=0
	no=0
  	while [ $i -lt $len ]
  	do
		if [ "${noiceWords[$i]}" = "${arr[0]}" ]; then
			isInNoiceWords=1
		fi
		((i++))
	done
	if [ "$isInNoiceWords" -eq "$no" ]; then
		lines[$numberOfLines]=${line}
		((numberOfLines++))	
	fi
done
echo "$originNumberOfLines"
i=0
while [ $i -lt $numberOfLines ]; do
	echo ${lines[$i]}
	((i++))	
done
