#!/bin/bash
returnVal=""
numberOfLines=0
while IFS='' read -r line || [[ -n "$line" ]]; do
  arr=($line)
  len=${#arr[@]}
  i=0
  while [ $i -lt $len ]
  do
    j=$i
    string=""
    newI=$(( $i + $len ))
    while [ $j -lt $newI ]; do
       string="$string ${arr[$j]}"
      ((j++))
    done
    arr[$newI]=${arr[$i]}
    if [ "$numberOfLines" -eq "0" -a "$i" -eq "0" ]; 
    then
       returnVal="$string"
    else
       returnVal="$returnVal"$'\n'"$string"
    fi
    ((i++))
  done
((numberOfLines++))
done < "$1"
echo "$1 $numberOfLines"
echo "$returnVal"
