#!/bin/bash
index=-1;
strindex() {
  x="${1%%$2*}"
  [[ $x = $1 ]] && index=-1 || index=${#x}
}

#create directory
echo "Enter the name of the directory where the file will be unzipped: "
read dirName

#unzip
unzip  cis361p4.zip -d $dirName

FILES=$dirName/*
for f in $FILES
do
  #substring to the beginning of the username
  Username=${f:${#dirName}+11}
  strindex "$Username" "_"
  Username=${Username:0:$index}

  #create the dir if it does not exits
  if [ ! -d "$dirName/$Username" ]; then
    mkdir $dirName/$Username
    echo "Created $dirName/$Username"
  fi
  #find file name
  fileName=${f:${#dirName}+40:${#f}}
  strindex "$fileName" "_"
  if [ $index == -1 ]; then
    fileName="memo.txt"
  else
    fileName=${fileName:$index+1:${#f}}
  fi
  #move the file to the user's dir
  mv "$f" "$fileName"
  mv "$fileName" "$dirName/$Username"
  echo "Moved $fileName to $dirName/$Username"

  if [ "$fileName" == "makefile" ]; then
    $dirName/$Username/./makefile
    ./cipher 1 test LetFreq.txt out.txt
  fi
done
